export enum State {
  // Shared subset used by both flows
  START = "START",
  CONSENT = "CONSENT",
  AGENDA = "AGENDA",
  DEMOGRAPHICS = "DEMOGRAPHICS",
  MEDICAL_HISTORY = "MEDICAL_HISTORY",
  MEDICATIONS = "MEDICATIONS",
  SYSTEMS_REVIEW = "SYSTEMS_REVIEW",
  PREVENTIVE = "PREVENTIVE",
  SUMMARY = "SUMMARY",
  END = "END"
}
