/**
 * Medical Reasoning Engine Types
 * 
 * Core interfaces for medical reasoning, red flag detection,
 * and clinical decision support.
 */

/**
 * Represents a medical red flag that requires attention
 */
export interface RedFlag {
  id: string;
  label: string;
  reason: string;
  severity: "low" | "moderate" | "high";
}

/**
 * Computed health scores from analysis
 */
export interface ReasoningScores {
  bmi?: number;
  cardioRisk?: number;
  respiratorySeverity?: number;
  depressionScore?: number;
  [key: string]: number | undefined;
}

/**
 * Recommendations generated by the reasoning engine
 */
export interface ReasoningRecommendations {
  /** Topics for patient education */
  educationTopics: string[];
  /** Suggested preventive screenings */
  screeningSuggestions: string[];
  /** Additional questions to ask */
  followUpQuestions: string[];
}

/**
 * Complete result from the reasoning engine analysis
 */
export interface ReasoningResult {
  /** Detected red flags requiring attention */
  redFlags: RedFlag[];
  /** Computed health scores */
  scores: ReasoningScores;
  /** Generated recommendations */
  recommendations: ReasoningRecommendations;
  /** Clinical notes for the session */
  notes: string[];
  /** Optional state override (e.g., escalate to urgent care) */
  overrideNextState?: string;
}

/**
 * Context provided to the reasoning engine for analysis
 */
export interface ReasoningContext {
  userId: string;
  sessionId: string;
  /** Current state machine state */
  state: string;
  /** User input for current node */
  input: unknown;
  /** Session memory/context */
  memory: Record<string, unknown>;
  /** Risk calculation utilities */
  risk?: RiskUtils;
  /** Screening logic utilities */
  screening?: ScreeningUtils;
}

/**
 * Risk calculation utilities interface
 */
export interface RiskUtils {
  computeBMI?(weightKg: number, heightM: number): number;
  computeChestPainRisk?(text: string, memory: Record<string, unknown>): number;
  respiratorySeverityScore?(input: unknown): number;
}

/**
 * Screening logic utilities interface
 */
export interface ScreeningUtils {
  detectCardioRedFlags?(text: string): string | null;
  recommendScreenings?(age: number, sex: string): string[];
}

/**
 * Interface for medical reasoning engine implementations
 */
export interface IMedicalReasoningEngine {
  /**
   * Analyze patient context and return reasoning results
   */
  analyze(ctx: ReasoningContext): Promise<ReasoningResult>;
}

