export enum State {
    GREET = "GREET",
    COLLECT_BASIC_INFO = "COLLECT_BASIC_INFO",
    SCREENING = "SCREENING",
    WELLNESS_EDUCATION = "WELLNESS_EDUCATION",
    FOLLOW_UP = "FOLLOW_UP",
    END = "END"
  }
  