export enum State {
  // === Core states (used by MVP and Full flows) ===
  START = "START",
  CONSENT = "CONSENT",
  AGENDA = "AGENDA",
  DEMOGRAPHICS = "DEMOGRAPHICS",
  MEDICAL_HISTORY = "MEDICAL_HISTORY",
  MEDICATIONS = "MEDICATIONS",
  SYSTEMS_REVIEW = "SYSTEMS_REVIEW",
  PREVENTIVE = "PREVENTIVE",
  SUMMARY = "SUMMARY",
  END = "END",

  // === Extended states (used by Extended flow) ===
  // Original legacy states
  GREET = "GREET",
  COLLECT_BASIC_INFO = "COLLECT_BASIC_INFO",
  SCREENING = "SCREENING",
  WELLNESS_EDUCATION = "WELLNESS_EDUCATION",
  FOLLOW_UP = "FOLLOW_UP",

  // Privacy & consent
  PRIVACY_SUMMARY = "PRIVACY_SUMMARY",
  EPHEMERAL_CONSENT = "EPHEMERAL_CONSENT",

  // Demographics extended
  DEMOGRAPHICS_ASKAGE = "DEMOGRAPHICS_ASKAGE",

  // Medical history extended
  MED_HISTORY_FOLLOWUP = "MED_HISTORY_FOLLOWUP",

  // Additional data collection
  ALLERGIES = "ALLERGIES",
  SOCIAL_HISTORY = "SOCIAL_HISTORY",

  // Systems review (detailed)
  SYSTEMS_REVIEW_INTRO = "SYSTEMS_REVIEW_INTRO",
  SYSTEMS_CARDIO = "SYSTEMS_CARDIO",
  SYSTEMS_CARDIO_FOLLOWUP = "SYSTEMS_CARDIO_FOLLOWUP",
  SYSTEMS_RESP = "SYSTEMS_RESP",
  SYSTEMS_RESP_FOLLOWUP = "SYSTEMS_RESP_FOLLOWUP",
  SYSTEMS_GI = "SYSTEMS_GI",
  SYSTEMS_NEURO = "SYSTEMS_NEURO",
  SYSTEMS_MSK = "SYSTEMS_MSK",
  SYSTEMS_PSYCH = "SYSTEMS_PSYCH",

  // Mental health screening
  PHQ2 = "PHQ2",
  PHQ2_Q2 = "PHQ2_Q2",

  // Preventive care (detailed)
  PREVENTIVE_SCREENINGS = "PREVENTIVE_SCREENINGS",
  PREVENTIVE_CHECKLIST = "PREVENTIVE_CHECKLIST",
  PREVENTIVE_LIPIDS = "PREVENTIVE_LIPIDS",
  PREVENTIVE_DIABETES = "PREVENTIVE_DIABETES",
  VACCINATIONS = "VACCINATIONS",

  // Summary & saving
  SUMMARY_PLAN = "SUMMARY_PLAN",
  SAVING_AND_REMINDERS = "SAVING_AND_REMINDERS",
  SAVING = "SAVING",

  // Escalation
  ESCALATE = "ESCALATE",
  ESCALATE_SUMMARY = "ESCALATE_SUMMARY",

  // End states (multiple outcomes)
  END_OK = "END_OK",
  END_ESCALATED = "END_ESCALATED",
  END_EPHEMERAL = "END_EPHEMERAL",
  END_NOSESSION = "END_NOSESSION"
}
